name: steamgiftsbot
base: core18
#version: '0.3.1'
adopt-info: sgbot
summary: Bot for steamgifts.com
description: |
    The cookie is PHPSESSID, you can obtain it after logging in site.

grade: stable
confinement: strict 

parts:
  sgbot:
    source: https://github.com/knightpp/steamgifts-bot.git
    plugin: cmake
    configflags:
        - "-DSNAP_BUILD=1"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DCMAKE_INSTALL_PREFIX=/"
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version "$(git describe --long)"
    build-packages:
      - g++
      - make
      - libcurl3-gnutls-dev
      - libhtmlcxx-dev
      - git
    stage-packages:
      - libcurl3-gnutls
      - libhtmlcxx3v5
      

apps:
    steamgiftsbot:
        command: bin/steamgiftsbot
        plugs: [network]
        #extensions: [gnome-3-28]

